<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<Deterministic>true</Deterministic>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="dist\**" />
	  <EmbeddedResource Remove="dist\**" />
	  <None Remove="dist\**" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="prompt_SLE.txt" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="BepInEx">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Valheim\BepInEx\core\BepInEx.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Valheim\BepInEx\core\0Harmony.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\UnityEngine.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\UnityEngine.UI.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\Assembly-CSharp.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="assembly_valheim">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\assembly_valheim.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="assembly_utils">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\assembly_utils.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="assembly_guiutils">
			<HintPath>C:\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed\assembly_guiutils.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>
</Project>
